### PR TITLE
Migrate project to androidx

### PR DESCRIPTION
**Pull request by milis92**
Migrate the library to latest stable androidx libraries which solves #492

### CODE REVIEW

**Comment by f0restgump92** [comment]
Also i was facing `MatisseActivity does not implement interface 'androidx.lifecycle.LifecycleOwner` when i migrated my own projects to androidx and this PR fixes that as well

**Comment by Sh1d0w** [comment]
Thanks for the PR! Is there any chance this will get merged soon @REBOOTERS

**Comment by etceterakong** [comment]
项目升级AndroidX后也遇到了Class 'com.zhihu.matisse.ui.MatisseActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner' in call to 'androidx.lifecycle.Lifecycle androidx.lifecycle.LifecycleOwner.getLifecycle()' (declaration of 'androidx.lifecycle.LiveData' appears in /data/app/com.hisensoft.bustong-5bowrZ6kZ3Jx1VQ7-kNs2g==/base.apk:classes2.dex)问题。请教一下这个问题需要怎样解决，谢谢！

**Comment by jiangyaokai-whalevii** [comment]
请问何时merge呢？

**Pull request merged**
