### PR TITLE
Android q

### PR DESCRIPTION
**Pull request by yccheok**
同志好！

我尝试修复 Android Q 的臭虫。因为我对 CursorLoader 并不了解。如果你能找出更好的方案，请修正。

谢谢同志们！

> Support Android Q.
> 
> 1) "COUNT(*) AS " + COLUMN_COUNT is not working in Android Q anymore (Not sure why)
> 2) There are no official document specific how GROUP BY should work in CursorLoader. The unofficial workaround seem no longer work in Android Q - https://stackoverflow.com/a/33367564/72437
> 
> Due to the above 2 limitations, we need to perform manual calculation on "count per directory".

### CODE REVIEW

**Review by REBOOTERS — APPROVED** [review]

**Comment by bhargavsavasani** [comment]
E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
    Process: com.CCS.WeCards, PID: 5336
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalArgumentException: Invalid column COUNT(*) AS count
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at androidx.core.content.ContentResolverCompat.query(ContentResolverCompat.java:81)
        at androidx.loader.content.CursorLoader.loadInBackground(CursorLoader.java:63)
        at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:97)
        at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:33)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 

Getting the Same issue on Android Q

**Comment by yccheok** [comment]
@BhargavSavasani 

    at com.zhihu.matisse.internal.loader.AlbumLoader.loadInBackground(AlbumLoader.java:97)

doesn't seem like latest code base.

Providing crash log alone wouldn't help much. You need to provide more detail on how we can reproduce the problem. Only then we can resolve the problem.

I had tested the following :

- Latest commit https://github.com/zhihu/Matisse/tree/21591aebe73a56435d84afc7b5cd50ea7ae2a6b8

- Android 10.0 Q Emulator

I tried to browse the gallery and select an 2 images. No issue found so far. Please see my screenshots.

**Comment by bhargavsavasani** [comment]
@yccheok 
ok, Now it's Working 
Thanks

**Comment by erichyx** [comment]
@yccheok 项目里配置混淆之后，在Android Q上显示不了图片。
image

**Pull request merged**
