### PR TITLE
Fixes a problem where temporary files are created in the wrong location

### PR DESCRIPTION
**Pull request by cgpathos**

### CODE REVIEW

**Comment by gejiaheng** [comment]
@cgpathos 
May I ask when will this bug be reproduced?

**Comment by cgpathos** [comment]
I can hard to explain reproduce this bug
but I tested the other two devices and got the same results.

```java
String imageFileName = "JPEG_20170425_212417_";

if (mCaptureStrategy.isPublic) {
    storageDir = Environment.getExternalStoragePublicDirectory(
            Environment.DIRECTORY_PICTURES);  // result is "/storage/emulated/0/Pictures"
} else {
    storageDir = mContext.get().getExternalFilesDir(Environment.DIRECTORY_PICTURES); // result is "/storage/emulated/0/Android/data/com.zhihu.matisse.sample/files/Pictures"
}

return new File(storageDir + imageFileName + ".jpg"); // result is /storage/emulated/0/PicturesJPEG_20170425_212417_.jpg
```

this is my test devices info
```
galaxy note5 SM-920L(6.0.1)
nexus 5x(O preview1)
```

I hope this info can help you.

**Comment by cgpathos** [comment]
I realized after commented my code is not good enough.
I think this is better solution.
```java
// return new File(storageDir + imageFileName + ".jpg");
return new File(storageDir, imageFileName + ".jpg");
```

**Comment by gejiaheng** [comment]
@cgpathos 
Would `return new File(storageDir, imageFileName + ".jpg");` handle both situations?

**Comment by cgpathos** [comment]
yep!  
I tested the values ​​by manipulating them.
Like this code down below.
```java
return new File(storageDir.getPath() + "/", imageFileName + ".jpg"); // result : "/storage/emulated/0/Pictures/JPEG_20170426_125058_.jpg"
```

**Comment by gejiaheng** [comment]
@cgpathos 
Great! Would you please remove last commit and push the new code so I can merge this PR?

**Comment by unixzii** [comment]
@gejiaheng @cgpathos 
I fixed this issue in my newest PR by using `File(File parent, String child)` constructor, it can handle the path joining directly.

**Comment by cgpathos** [comment]
@unixzii 's PR has fix this issue.
so I'm ok with reject my PR. 

@gejiaheng

**Comment by gejiaheng** [comment]
@cgpathos 
Thank you anyway. You're always welcomed to contribute.

**Comment by gejiaheng** [comment]
This PR will be closed due to an existing fixing PR https://github.com/zhihu/Matisse/pull/26

**Pull request closed without merging**
