### PR TITLE
feat: add ability to get paths

### PR DESCRIPTION
**Pull request by eprendre**
I need to upload pictures. However, the `mCurrentPhotoUri` created by `FileProvider` is for intent to start camera. We can't get file path from `mCurrentPhotoUri`, according to http://stackoverflow.com/a/39962512/4739220. 

I added `obtainPathResult` to get path directly from `capture`, as well as resolving paths from album uri.

### CODE REVIEW

**Comment by gejiaheng** [comment]
@eprendre 
After I merged this PR, IDE found an error in `file_paths_public.xml` which is:  
>Value must not be empty.
Line: 20

Would you please fix it?

**Comment by eprendre** [comment]
Oops, there's no error in my IDE. You can change back to `path="Pictures`.

**Comment by gejiaheng** [comment]
@eprendre 
Why do you change it to a empty value at first? Is the `Pictures` value not working on some specific occasions?

**Comment by eprendre** [comment]
Soz, it's just my guess. I should not commit this file.

**Comment by gejiaheng** [comment]
@eprendre 
It's all right. Though Android Studio complains about it, the project still compiles successfully. I'll fix it with the sample update PR.

**Pull request merged**
