### PR TITLE
Add support for Coil image loader.

### PR DESCRIPTION
**Pull request by colinrtwhite**
Adds `CoilEngine` to support image loading via [Coil](https://github.com/coil-kt/coil).

### CODE REVIEW

**Review by YLPeng — APPROVED** [review]

**Comment by YLPeng** [comment]
Can we get this reviewed and merge?

**Comment by YLPeng** [comment]
@colinrtwhite  I tried to extract your `CoilEngine` file locally, but it seems not working for me, I can't see thumbnails from the media picker.

**Comment by colinrtwhite** [comment]
@YLPeng Hmm I just tested locally on my API 27 emulator and it seems to work OK.

**Comment by YLPeng** [comment]
@colinrtwhite  can you share the code how you configure Matisse with coil ? This is what I got:

```
Matisse.from(parentActivity)
                    .choose(MimeType.ofVideo())
                    .showSingleMediaType(true)
                    ...
                    .imageEngine(CoilCustomEngine(this.context))
                    .forResult(requestCode)```

**Comment by colinrtwhite** [comment]
What's `CoilCustomEngine`? I changed both `imageEngine` call sites to `imageEngine(new CoilEngine(this))`.

**Comment by YLPeng** [comment]
Thanks, I renamed `CoilEngine` to `CoilCustomEngine` when I copy your file to my local. 

Do you know if it works on video files?

**Comment by colinrtwhite** [comment]
Coil doesn't currently support video files. Only the first frame of the video will be decoded as an image.

**Comment by YLPeng** [comment]
yeah, first frame is fine, I just need a thumbnail of the video. Does your CoilEngine support that?

**Comment by colinrtwhite** [comment]
I believe so, but I haven't tested that.

**Comment by YLPeng** [comment]
@colinrtwhite  thanks for your help. I got it to work now, I implement my own way to get thumbnail from the video and load it using coil.

**Comment by colinrtwhite** [comment]
Closing as it seems like this project is abandoned.

**Pull request closed without merging**
