### PR TITLE
Mkdn typo: use 'gradle' instead of 'groovy'

### PR DESCRIPTION
**Pull request by imknown**
:D

### CODE REVIEW

**Comment by gejiaheng** [comment]
@imknown 
Thanks for your suggestion. But why 'gradle' instead of 'groovy'? It is Groovy language.

**Comment by imknown** [comment]
@gejiaheng Hi. `*.gradle` should use `gradle`.

Github official help here:
0. https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting
0. https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1515
0. https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L1562

**Comment by gejiaheng** [comment]
@imknown 
I checked a few popular Android projects on Github and didn't find any using `gradle` instead of `groovy`. And I wonder if it is necessary to use `gradle`. You can interpret the README snippet into Groovy language code snippet or gradle file snippet. So I think both are OK.

**Comment by imknown** [comment]
@gejiaheng :D haha, thx.

**Comment by gejiaheng** [comment]
@imknown 
Thanks anyway. For now it seems not a must modification, so I'll close this PR. You can reopen it if you have further informations.

**Pull request closed without merging**
